#! /usr/bin/env python

import sys, os


def capath():
	print 'CAPATH enviroment variable...',
	CAPATH = None
	try:
		CAPATH = os.environ['CAPATH']
	except:
		print '[Failed]'
	if CAPATH != None:
		if os.path.exists(os.path.join(CAPATH,'dist','softwarestudies.jar')):
			print '[Passed]'
		else:
			print '[Failed]'

def java():
	print 'Java Runtime.................',
	error = os.system('java -version')
	if error != 0:
		print '[Failed]'
	else:
		print '[Passed]'

def ffmpeg():
	print 'ffmpeg.......................',
	error = os.system('ffmpeg -version')
	if error != 0:
		print '[Failed]'
	else:
		print '[Passed]'

def convert():
	print 'ImageMagick [convert]........',
	error = os.system('convert -version')
	if error != 0:
		print '[Failed]'
	else:
		print '[Passed]'

def matlab():
	print 'Matlab.......................',
	sys.stdout.flush()
	error = os.system('matlab -nodisplay -nojvm -r "exit" > /dev/null')
	if error != 0:
		print '[Failed]'
	else:
		print '[Passed]'


def main():
	print 'Running tests for required software...'
	capath()
	java()
	ffmpeg()
	convert()
	matlab()

if __name__ == "__main__":
    main()
